// Carbon AI Chat'in arayüz metinleri, Türkçe (@carbon/ai-chat 1.22.0 enLanguagePack'in 263 anahtarı).
// Paket güncellenince `node --test tests/dil-paketi.test.ts` eksik anahtarı adıyla söyler.
import type { LanguagePack } from '@carbon/ai-chat'

export const TURKCE: LanguagePack = {
  ai_slug_label: 'Yapay zekâ açıklaması',
  ai_slug_title: 'Bu yanıtları bir yapay zekâ yazıyor',
  ai_slug_description: 'TEDY Asistanı yanıtlarını Claude ile yazar; okul verisi, MEB müfredatı ve ders kitapları kaynak olarak numaralanır. Yapay zekâ yanılabilir — bir şey tuhaf geldiyse kaynağa bak.',
  components_overflow_ariaLabel: 'Seçenek listesini aç veya kapat',
  components_swiper_currentLabel: '{currentSlideNumber}/{totalSlideCount}',
  errors_communicating: '{assistantName} şu an yanıt veremiyor. Bağlı bir sistemdeki sorun verinin gelmesini engelliyor.',
  errors_imageSource: 'Görsel kullanılamıyor.',
  errors_videoSource: 'Video kullanılamıyor.',
  errors_audioSource: 'Ses kullanılamıyor.',
  media_audioPlayer_loading: 'Ses oynatıcı yükleniyor',
  media_audioPlayer_ready: 'Ses oynatıcı hazır',
  media_audioPlayer_loadingLabel: 'Yükleniyor',
  media_audioPlayer_readyLabel: 'Hazır',
  media_audioPlayer_errorLabel: 'Hata',
  media_videoPlayer_loading: 'Video oynatıcı yükleniyor',
  media_videoPlayer_ready: 'Video oynatıcı hazır',
  media_videoPlayer_loadingLabel: 'Yükleniyor',
  media_videoPlayer_readyLabel: 'Hazır',
  media_videoPlayer_errorLabel: 'Hata',
  errors_iframeSource: 'Web sayfası kullanılamıyor.',
  errors_singleMessage: 'Gönderdiğin mesajda bir sorun oldu; başka bir şey sorabilirsin.',
  errors_ariaMessageRetrying: 'Mesaj gönderilirken sorun yaşanıyor, yeniden deneniyor',
  errors_ariaMessageFailed: 'Mesaj gönderilemedi',
  errors_noHumanAgentsAvailable: 'Şu an destek kişisi yok.',
  errors_noHumanAgentsJoined: 'Sohbete katılan destek kişisi olmadı',
  errors_connectingToHumanAgent: 'Bir sorun oldu; şu an bir destek kişisine bağlanılamıyor.',
  errors_busy: 'Şu an çok yoğunuz; biraz sonra yeniden dene.',
  errors_agentAppSessionExpired: 'Sohbet geçmişine erişimin süresi doldu.',
  errors_generalContent: 'Bu içerik gösterilirken bir hata oldu',
  errors_somethingWrong: 'Bir şeyler ters gitti',
  input_ariaLabel: 'Sorunu yaz',
  input_placeholder: 'Bir soru sor...',
  input_buttonLabel: 'Gönder',
  input_uploadButtonLabel: 'Dosya ekle',
  input_actionsMenuLabel: 'Dosya ve daha fazlası',
  input_actionsOverflowLabel: 'Diğer eylemler',
  input_sendingMessage: 'Mesaj gönderiliyor...',
  input_keyboardShortcutAnnouncement: 'Mesaj listesi ile giriş alanı arasında geçmek için {key} tuşuna bas.',
  input_maxCharCountExceeded: 'En çok {max} karakter yazılabilir. Şu an {current} karakter.',
  input_maxCharCountExceededTitle: 'Hata: karakter sınırı aşıldı',
  window_title: 'Sohbet penceresi',
  window_ariaChatRegion: 'Sohbet',
  window_ariaChatRegionNamespace: 'Sohbet {namespace}',
  window_ariaWindowOpened: 'Sohbet penceresi açıldı',
  window_ariaWindowClosed: 'Sohbet penceresi kapandı',
  window_ariaWindowLoading: 'Sohbet yükleniyor.',
  launcher_isOpen: 'Sohbet penceresini kapat',
  launcher_isClosed: 'Sohbet penceresini aç',
  launcher_desktopGreeting: 'Merhaba! Bugün nasıl yardımcı olabilirim?',
  launcher_mobileGreeting: 'Merhaba! Bugün nasıl yardımcı olabilirim?',
  launcher_ariaIsExpanded: 'Başlatıcı bildirimini kapat',
  launcher_closeButton: 'Kapat',
  media_transcript_label: 'Döküm',
  media_transcript_show: 'Göster',
  media_transcript_hide: 'Gizle',
  messages_youSaid: 'Sen yazdın',
  messages_attachmentsLabel: 'Ekler',
  messages_unnamedAttachment: 'Ek',
  messages_assistantSaid: '{assistantName} yazdı',
  messages_agentSaid: 'Destek kişisi yazdı',
  messages_searchResults: 'Arama sonuçları',
  messages_searchResultsLink: 'Bu sonucu yeni pencerede aç',
  messages_searchResultsOpenDocument: 'Belgeyi aç',
  messages_searchResultsOpenDocumentWithLabel: '"{documentName}" belgesini aç',
  messages_searchResultsExpand: 'Genişlet',
  messages_searchResultsCollapse: 'Daralt',
  messages_assistantIsLoading: '{assistantName} düşünüyor',
  messages_agentIsTyping: 'Destek kişisi yazıyor',
  messages_focusHandle: 'Mesajı seç',
  messages_processingLabel: 'İşleniyor',
  messages_scrollHandle: 'Sohbetin başı',
  messages_scrollHandleDetailed: 'Sohbetin başı. İlk mesaja gitmek için bu düğmeyi seç, mesajlar arasında ok tuşlarıyla gezin. Listeden çıkmak için Esc\'ye bas. Mesaj listesi ile giriş alanı arasında geçmek için {shortcut} tuşuna bas.',
  messages_scrollHandleDetailedNoShortcut: 'Sohbetin başı. İlk mesaja gitmek için bu düğmeyi seç, mesajlar arasında ok tuşlarıyla gezin. Listeden çıkmak için Esc\'ye bas.',
  messages_scrollHandleEnd: 'Sohbetin sonu',
  messages_scrollHandleEndDetailed: 'Sohbetin sonu. Son mesaja gitmek için bu düğmeyi seç, mesajlar arasında ok tuşlarıyla gezin. Listeden çıkmak için Esc\'ye bas. Mesaj listesi ile giriş alanı arasında geçmek için {shortcut} tuşuna bas.',
  messages_scrollHandleEndDetailedNoShortcut: 'Sohbetin sonu. Son mesaja gitmek için bu düğmeyi seç, mesajlar arasında ok tuşlarıyla gezin. Listeden çıkmak için Esc\'ye bas.',
  messages_scrollMoreButton: 'En alta in',
  messages_reasoningStart: '{sender} kaynaklara bakıyor...',
  messages_streamingStart: '{sender} yazıyor...',
  message_labelAssistant: '{actorName} {timestamp}',
  message_labelYou: 'Sen {timestamp}',
  buttons_restart: 'Sohbeti yeniden başlat',
  buttons_cancel: 'Vazgeç',
  buttons_retry: 'Tekrar dene',
  options_select: 'Bir seçenek seç',
  options_ariaOptionsDisabled: 'Bu seçenekler kapalı, seçilemez',
  header_previewLinkTitle: 'Asistan önizlemesi',
  header_ariaAssistantAvatar: '{assistantName} simgesi',
  header_overflowMenu_options: 'Seçenekler',
  history_view_chats: 'Sohbetleri gör',
  history_new_chat: 'Yeni sohbet',
  homeScreen_returnToAssistant: 'Sohbete dön',
  homeScreen_returnToHome: 'Başlangıç ekranına dön',
  homeScreen_overflowMenuHomeScreen: 'Başlangıç ekranı',
  homeScreen_ariaQuickStartListButton: 'Hızlı başlangıç menüsü',
  homeScreen_ariaQuickStartListOpened: 'Hızlı başlangıç menüsü açıldı.',
  homeScreen_ariaQuickStartListClosed: 'Hızlı başlangıç menüsü kapandı.',
  homeScreen_ariaHomeScreenContent: 'Başlangıç ekranı',
  homeScreen_shown: 'Başlangıç ekranı görünüyor',
  homeScreen_hidden: 'Sohbete dönüldü',
  default_agent_availableMessage: 'Destek kişisi iste; hazır olduğunda haber veririm.',
  default_agent_unavailableMessage: 'Şu an destek kişisi yok.',
  agent_reason_error: 'Bir sorun yaşıyorum; sohbete bir destek kişisinin devam etmesi gerekiyor.',
  agent_sdMissingWarning: 'Destek masası yapılandırılmamış.',
  agent_noName: 'Destek kişisi',
  agent_chatTitle: 'Canlı destek',
  agent_startChat: 'Destek kişisine bağlan',
  agent_connecting: 'İstek gönderildi...',
  agent_agentNoNameTitle: 'Destek',
  agent_agentJoinedName: '{personName} bağlandı.',
  agent_agentJoinedNoName: 'Bir destek kişisi bağlandı.',
  agent_youConnectedWarning: 'Sayfadan ayrılırsan yeniden destek istemen gerekir.',
  agent_connectingMinutes: 'Bekleme süresi <b>{time, number} dakika</b>.',
  agent_connectingQueue: 'Sırada <b>{position, number}.</b> sıradasın.',
  agent_ariaHumanAgentAvatar: 'Destek kişisinin simgesi',
  agent_ariaGenericAvatar: 'Simge',
  agent_ariaGenericAssistantAvatar: 'Simge',
  agent_youEndedChat: 'Destek kişisiyle bağlantıyı kestin.',
  agent_conversationWasEnded: 'Destek kişisiyle bağlantıyı kestin.',
  agent_disconnected: 'Bir sorun oldu, destek kişisiyle bağlantı koptu. İnternet bağlantını kontrol edip yeniden dene.',
  agent_reconnected: 'Destek kişisi yeniden bağlandı.',
  agent_agentLeftChat: '{personName} ayrıldı.',
  agent_agentLeftChatNoName: 'Destek kişisi ayrıldı.',
  agent_agentEndedChat: '{personName} sohbeti bitirdi.',
  agent_agentEndedChatNoName: 'Destek kişisi sohbeti bitirdi.',
  agent_transferring: 'Aktarılıyorsun.',
  agent_transferringNoName: 'Aktarılıyorsun.',
  agent_endChat: 'Destek kişisiyle bağlantı kesilsin mi?',
  agent_confirmSuspendedEndChatTitle: 'Önceki destek kişisiyle bağlantı kesilsin mi?',
  agent_confirmSuspendedEndChatMessage: 'Şu an bir destek kişisine bağlısın. Devam edersen bağlantı kesilip yenisine bağlanırsın. Devam edilsin mi?',
  agent_confirmCancelRequestTitle: 'İstek iptal edilsin mi?',
  agent_confirmCancelRequestMessage: 'Devam edersen destek isteğin iptal edilir.',
  agent_confirmCancelRequestNo: 'Geri dön',
  agent_confirmCancelRequestYes: 'İsteği iptal et',
  agent_confirmEndChat: 'Bağlantıyı kesersen yeniden destek istemen gerekir.',
  agent_confirmEndChatNo: 'Geri dön',
  agent_confirmEndChatYes: 'Bağlantıyı kes',
  agent_confirmEndSuspendedYes: 'Devam et',
  agent_assistantReturned: 'Başka bir konuda yardımcı olabilir miyim?',
  agent_newMessage: 'Yeni mesaj',
  agent_cardButtonChatRequested: 'Bağlanıyor...',
  agent_cardButtonConnected: 'Bağlandı',
  agent_cardButtonChatEnded: 'Bağlantı kesildi',
  agent_cardMessageChatEnded: 'Destek kişisiyle bağlantıyı kestin.',
  agent_cardMessageConnected: 'Artık bağlısın.',
  agent_connectButtonCancel: 'Vazgeç',
  agent_connectedButtonEndChat: 'Bağlantıyı kes',
  agent_connectWaiting: 'Bekleniyor...',
  agent_defaultMessageToHumanAgent: 'Sohbeti başlat',
  agent_inputPlaceholderConnecting: 'Destek kişisi bekleniyor...',
  agent_inputPlaceholderReconnecting: 'Yeniden bağlanılıyor...',
  agent_sharingStopSharingButton: 'Ekran paylaşımını durdur',
  agent_sharingRequestTitle: 'Ekran paylaşımı',
  agent_sharingRequestMessage: 'Destek kişisi ekranını paylaşmanı istedi. İstediğin zaman durdurabilirsin.',
  agent_sharingAcceptButton: 'Ekranı paylaş',
  agent_sharingDeclineButton: 'Reddet',
  agent_sharingRequested: 'Ekranını paylaşman istendi.',
  agent_sharingAccepted: 'Ekranını paylaştın.',
  agent_sharingDeclined: 'Ekran paylaşımını reddettin.',
  agent_sharingCancelled: 'Ekran paylaşım isteği iptal edildi.',
  agent_sharingEnded: 'Ekran paylaşımını durdurdun.',
  agent_suspendedWarning: 'Şu an bir destek kişisine bağlısın.',
  icon_ariaUnreadMessages: '{count, number} okunmamış mesaj var',
  showMore: 'Devamını gör',
  showMoreResults: 'Devamını gör',
  disclaimer_title: 'Uyarı',
  disclaimer_accept: 'Kabul ediyorum',
  disclaimer_icon_label: 'Uyarı simgesi',
  disclaimer_acceptance_label: 'Uyarı onayı',
  general_ariaCloseInformationOverlay: 'Bilgi panelini kapat.',
  general_ariaAnnounceOpenedInformationOverlay: 'Bir bilgi paneli açıldı.',
  general_ariaAnnounceClosedInformationOverlay: 'Bilgi paneli kapandı.',
  general_ariaAnnounceEscapeOverlay: 'Kapatmak için Esc\'ye bas ya da kapat düğmesini seç.',
  general_returnToAssistant: 'Sohbete dön',
  conversationalSearch_streamingIncomplete: 'Bu mesaj tamamlanamadı. Yeniden dene.',
  conversationalSearch_viewSourceDocument: 'Kaynağı gör',
  conversationalSearch_citationsLabel: 'Kaynaklar',
  conversationalSearch_toggleCitations: 'Kaynak listesini aç veya kapat',
  conversationalSearch_responseStopped: 'Yanıt durduruldu',
  iframe_ariaSourceLoaded: 'Web sayfası yüklendi.',
  iframe_ariaImageAltText: 'Web sayfası panelinin önizleme görseli.',
  iframe_ariaClosePanel: 'Web sayfası panelini kapat.',
  iframe_ariaOpenedPanel: 'Web sayfası paneli açıldı.',
  iframe_ariaClosedPanel: 'Web sayfası paneli kapandı.',
  iframe_ariaClickPreviewCard: '{source} sayfasını panelde açmak için tıkla.',
  datePicker_chooseDate: 'Tarih seç ({format})',
  datePicker_confirmDate: 'Tarihi onayla',
  fileSharing_fileTooLarge: 'Dosya en çok {maxSize} olabilir.',
  fileSharing_ariaAnnounceSuccess: 'Dosya yüklendi.',
  fileSharing_fileIcon: 'Dosya simgesi',
  fileSharing_removeButtonTitle: 'Dosyayı kaldır',
  fileSharing_removeButtonTitleWithName: 'Kaldır: {filename}',
  fileSharing_statusUploading: 'Dosya yükleniyor',
  fileSharing_uploadFailed: 'Dosya yüklenemedi.',
  fileSharing_uploadErrorTitle: 'Yükleme hatası',
  fileSharing_uploadErrorRecovery: 'Eki kaldırıp yeniden dene.',
  fileSharing_agentMessageText: 'Dosya yükleme',
  fileSharing_request: 'Destek kişisi bir dosya yüklemeni istedi.',
  fileSharing_ariaAnnounceFilesAdded: '{count, plural, one {Dosya eklendi.} other {{count, number} dosya eklendi.}}',
  fileSharing_ariaAnnounceFilesUploading: '{count, plural, one {Dosya yükleniyor.} other {{count, number} dosya yükleniyor.}}',
  fileSharing_ariaAnnounceFileRemoved: 'Dosya kaldırıldı.',
  fileSharing_unsupportedType: '{filename} desteklenen bir dosya türü değil.',
  fileSharing_tooManyFiles: 'Bir mesaja en fazla {maxFiles} dosya eklenebilir.',
  carousel_prevNavButton: 'Önceki slayt.',
  carousel_nextNavButton: 'Sonraki slayt.',
  input_completionsTagApp: 'Uygulama',
  input_completionsTagAssistant: 'Asistan',
  table_filterPlaceholder: 'Tabloyu süz',
  table_previousPage: 'Önceki sayfa',
  table_nextPage: 'Sonraki sayfa',
  table_itemsPerPage: 'Sayfa başına:',
  table_paginationSupplementalText: '/ {pagesCount, number} sayfa',
  table_paginationStatus: '{start, number}–{end, number} / {count, number} öğe',
  codeSnippet_feedback: 'Kopyalandı!',
  codeSnippet_showLessText: 'Daha az göster',
  codeSnippet_showMoreText: 'Daha fazla göster',
  codeSnippet_tooltipContent: 'Panoya kopyala',
  codeSnippet_lineCount: '{count, number} satır',
  codeSnippet_foldCollapse: 'Kod bloğunu daralt',
  codeSnippet_foldExpand: 'Kod bloğunu genişlet',
  codeSnippet_ariaLabelReadOnly: 'Kod parçası',
  codeSnippet_ariaLabelReadOnlyWithLanguage: '{language} kod parçası',
  codeSnippet_ariaLabelEditable: 'Kod düzenleyici',
  codeSnippet_ariaLabelEditableWithLanguage: '{language} kod düzenleyici',
  table_downloadButton: 'Tablo verisini indir',
  feedback_positiveLabel: 'Bu yanıtı beğendim',
  feedback_negativeLabel: 'Bu yanıtı beğenmedim',
  feedback_defaultTitle: 'Geri bildirim',
  feedback_defaultPrompt: 'Neden bu değerlendirmeyi seçtin?',
  feedback_defaultPlaceholder: 'Yorum ekle',
  feedback_categoriesLabel: 'Geri bildirim türü',
  feedback_submitLabel: 'Geri bildirimi gönder',
  feedback_cancelLabel: 'Vazgeç',
  input_stopResponse: 'Yanıtı durdur',
  messages_responseStopped: 'Yanıt durduruldu',
  messages_requestCancelled: 'İstek iptal edildi',
  chainOfThought_stepTitle: '{stepNumber, number}: {stepTitle}',
  chainOfThought_inputLabel: 'Girdi',
  chainOfThought_outputLabel: 'Çıktı',
  chainOfThought_toolLabel: 'Araç',
  chainOfThought_statusSucceededLabel: 'Tamamlandı',
  chainOfThought_statusFailedLabel: 'Başarısız',
  chainOfThought_statusProcessingLabel: 'Sürüyor',
  chainOfThought_explainabilityLabel: 'Bu cevaba nasıl ulaştım?',
  reasoningSteps_mainLabelOpen: 'Adımları gizle',
  reasoningSteps_mainLabelClosed: 'Adımları göster',
  workspace_opened: 'Panel açıldı: {title}',
  workspace_opened_no_title: 'Panel açıldı',
  workspace_closed: 'Panel kapandı, sohbete dönüldü',
  panel_opened: 'Panel açıldı',
  panel_closed: 'Panel kapandı',
  history_shown: 'Sohbet geçmişi görünüyor',
  history_hidden: 'Sohbet geçmişi gizlendi',
  aria_workspaceRegion: 'Çalışma paneli',
  aria_historyRegion: 'Sohbet geçmişi',
  aria_messagesRegion: 'Sohbet mesajları',
  aria_catastrophicErrorPanel: 'Hata paneli',
  aria_hydrationPanel: 'Yükleme paneli',
  aria_customPanel: 'Panel',
  aria_disclaimerPanel: 'Uyarı paneli',
  aria_responsePanel: 'Yanıt paneli',
  aria_iframePanel: 'İçerik paneli',
  aria_viewSourcePanel: 'Kaynak paneli',
}

/** Aileye "siz" (CLAUDE.md hitap kuralı): cümle biçimli metinler aile okurken bunlarla değişir. Düğme adları
 *  ("Gönder", "Mesajı seç") arayüz komutudur, değişmez. Destek kişisi (canlı temsilci) metinleri kullanılmıyor. */
export const AILE: Partial<LanguagePack> = {
  errors_singleMessage: 'Gönderdiğiniz mesajda bir sorun oldu; başka bir şey sorabilirsiniz.',
  errors_busy: 'Şu an çok yoğunuz; biraz sonra yeniden deneyin.',
  input_ariaLabel: 'Sorunuzu yazın',
  input_keyboardShortcutAnnouncement: 'Mesaj listesi ile giriş alanı arasında geçmek için {key} tuşuna basın.',
  messages_youSaid: 'Siz yazdınız',
  message_labelYou: 'Siz {timestamp}',
  messages_scrollHandleDetailed: 'Sohbetin başı. İlk mesaja gitmek için bu düğmeyi seçin, mesajlar arasında ok tuşlarıyla gezinin. Listeden çıkmak için Esc\'ye basın. Mesaj listesi ile giriş alanı arasında geçmek için {shortcut} tuşuna basın.',
  messages_scrollHandleDetailedNoShortcut: 'Sohbetin başı. İlk mesaja gitmek için bu düğmeyi seçin, mesajlar arasında ok tuşlarıyla gezinin. Listeden çıkmak için Esc\'ye basın.',
  messages_scrollHandleEndDetailed: 'Sohbetin sonu. Son mesaja gitmek için bu düğmeyi seçin, mesajlar arasında ok tuşlarıyla gezinin. Listeden çıkmak için Esc\'ye basın. Mesaj listesi ile giriş alanı arasında geçmek için {shortcut} tuşuna basın.',
  messages_scrollHandleEndDetailedNoShortcut: 'Sohbetin sonu. Son mesaja gitmek için bu düğmeyi seçin, mesajlar arasında ok tuşlarıyla gezinin. Listeden çıkmak için Esc\'ye basın.',
  options_select: 'Bir seçenek seçin',
  general_ariaAnnounceEscapeOverlay: 'Kapatmak için Esc\'ye basın ya da kapat düğmesini seçin.',
  conversationalSearch_streamingIncomplete: 'Bu mesaj tamamlanamadı. Yeniden deneyin.',
  fileSharing_uploadErrorRecovery: 'Eki kaldırıp yeniden deneyin.',
  feedback_defaultPrompt: 'Neden bu değerlendirmeyi seçtiniz?',
}
